version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: class5_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies-database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql:Z
    networks:
      - class5_net

networks:
  class5_net:
    driver: bridge
